# В этом файлике лежит манифест деплоймента.
# Он совершенно точно сломан.
# После починки манифест должен корректно применяться
# и выкатывать 3 реплики версии 1.0
# И делать Rolling update, без даунтайма, выкатывая новую
# версию по одной.
# Написать с нуля новый - проще и быстрее. А чинить этот - веселее

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [app, web]}
  progressDeadlineSeconds: &integer 20
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: avtandilko/web:1.0
        readinessProbe:
          httpGet:
            path: /ping.txt
            port: &int 8000
          initialDelaySeconds: 10
          periodSeconds: 3
        lifecycle:
          preStop: 
            exec:
              command: ['sh', '-c', 'echo -n "Goodbye, cruel world!" > /dev/termination-log; sleep 5; kill -2 1']
          postStart:
            exec:
              command: ['sh', '-c', 'echo "I am OK!" > /app/ping.txt']
        volumeMounts:
        - name: app
          mountPath: /app
      initContainers:
        - name: html-gen
          image: busybox:1.31.0
          command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
          volumeMounts:
            - name: app
              mountPath: /app
        - name: sleepy-one
          image: busybox:musl
          command: ['sh', '-c', 'sleep 30']
      volumes:
        - name: app
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
